using EnergyPerformance.Models;

namespace EnergyPerformance.Helpers
{
    public static class LocalAuthorities
    {
        public static List<LocalAuthority> GetLocalAuthorities()
        {
            return new List<LocalAuthority>
            {
                new LocalAuthority { Code = "E07000223", Description = "Adur" },
                new LocalAuthority { Code = "E07000026", Description = "Allerdale" },
                new LocalAuthority { Code = "E07000032", Description = "Amber Valley" },
                new LocalAuthority { Code = "E07000224", Description = "Arun" },
                new LocalAuthority { Code = "E07000170", Description = "Ashfield" },
                new LocalAuthority { Code = "E07000105", Description = "Ashford" },
                new LocalAuthority { Code = "E07000004", Description = "Aylesbury Vale" },
                new LocalAuthority { Code = "E07000200", Description = "Babergh" },
                new LocalAuthority { Code = "E09000002", Description = "Barking and Dagenham" },
                new LocalAuthority { Code = "E09000003", Description = "Barnet" },
                new LocalAuthority { Code = "E08000016", Description = "Barnsley" },
                new LocalAuthority { Code = "E07000027", Description = "Barrow-in-Furness" },
                new LocalAuthority { Code = "E07000066", Description = "Basildon" },
                new LocalAuthority { Code = "E07000084", Description = "Basingstoke and Deane" },
                new LocalAuthority { Code = "E07000171", Description = "Bassetlaw" },
                new LocalAuthority { Code = "E06000022", Description = "Bath and North East Somerset" },
                new LocalAuthority { Code = "E06000055", Description = "Bedford" },
                new LocalAuthority { Code = "E09000004", Description = "Bexley" },
                new LocalAuthority { Code = "E08000025", Description = "Birmingham" },
                new LocalAuthority { Code = "E07000129", Description = "Blaby" },
                new LocalAuthority { Code = "E06000008", Description = "Blackburn with Darwen" },
                new LocalAuthority { Code = "E06000009", Description = "Blackpool" },
                new LocalAuthority { Code = "W06000019", Description = "Blaenau Gwent" },
                new LocalAuthority { Code = "E07000033", Description = "Bolsover" },
                new LocalAuthority { Code = "E08000001", Description = "Bolton" },
                new LocalAuthority { Code = "E07000136", Description = "Boston" },
                new LocalAuthority { Code = "E06000058", Description = "Bournemouth, Christchurch and Poole" },
                new LocalAuthority { Code = "E06000036", Description = "Bracknell Forest" },
                new LocalAuthority { Code = "E08000032", Description = "Bradford" },
                new LocalAuthority { Code = "E07000067", Description = "Braintree" },
                new LocalAuthority { Code = "E07000143", Description = "Breckland" },
                new LocalAuthority { Code = "E09000005", Description = "Brent" },
                new LocalAuthority { Code = "E07000068", Description = "Brentwood" },
                new LocalAuthority { Code = "W06000013", Description = "Bridgend" },
                new LocalAuthority { Code = "E06000043", Description = "Brighton and Hove" },
                new LocalAuthority { Code = "E06000023", Description = "Bristol, City of" },
                new LocalAuthority { Code = "E07000144", Description = "Broadland" },
                new LocalAuthority { Code = "E09000006", Description = "Bromley" },
                new LocalAuthority { Code = "E07000234", Description = "Bromsgrove" },
                new LocalAuthority { Code = "E07000095", Description = "Broxbourne" },
                new LocalAuthority { Code = "E07000172", Description = "Broxtowe" },
                new LocalAuthority { Code = "E06000060", Description = "Buckinghamshire" },
                new LocalAuthority { Code = "E07000117", Description = "Burnley" },
                new LocalAuthority { Code = "E08000002", Description = "Bury" },
                new LocalAuthority { Code = "W06000018", Description = "Caerphilly" },
                new LocalAuthority { Code = "E08000033", Description = "Calderdale" },
                new LocalAuthority { Code = "E07000008", Description = "Cambridge" },
                new LocalAuthority { Code = "E09000007", Description = "Camden" },
                new LocalAuthority { Code = "E07000192", Description = "Cannock Chase" },
                new LocalAuthority { Code = "E07000106", Description = "Canterbury" },
                new LocalAuthority { Code = "W06000015", Description = "Cardiff" },
                new LocalAuthority { Code = "E07000028", Description = "Carlisle" },
                new LocalAuthority { Code = "W06000010", Description = "Carmarthenshire" },
                new LocalAuthority { Code = "E07000069", Description = "Castle Point" },
                new LocalAuthority { Code = "E06000056", Description = "Central Bedfordshire" },
                new LocalAuthority { Code = "W06000008", Description = "Ceredigion" },
                new LocalAuthority { Code = "E07000130", Description = "Charnwood" },
                new LocalAuthority { Code = "E07000070", Description = "Chelmsford" },
                new LocalAuthority { Code = "E07000078", Description = "Cheltenham" },
                new LocalAuthority { Code = "E07000177", Description = "Cherwell" },
                new LocalAuthority { Code = "E06000049", Description = "Cheshire East" },
                new LocalAuthority { Code = "E06000050", Description = "Cheshire West and Chester" },
                new LocalAuthority { Code = "E07000034", Description = "Chesterfield" },
                new LocalAuthority { Code = "E07000225", Description = "Chichester" },
                new LocalAuthority { Code = "E07000005", Description = "Chiltern" },
                new LocalAuthority { Code = "E07000118", Description = "Chorley" },
                new LocalAuthority { Code = "E09000001", Description = "City of London" },
                new LocalAuthority { Code = "E07000071", Description = "Colchester" },
                new LocalAuthority { Code = "W06000003", Description = "Conwy" },
                new LocalAuthority { Code = "E07000029", Description = "Copeland" },
                new LocalAuthority { Code = "E07000150", Description = "Corby" },
                new LocalAuthority { Code = "E06000052", Description = "Cornwall" },
                new LocalAuthority { Code = "E07000079", Description = "Cotswold" },
                new LocalAuthority { Code = "E06000047", Description = "County Durham" },
                new LocalAuthority { Code = "E08000026", Description = "Coventry" },
                new LocalAuthority { Code = "E07000163", Description = "Craven" },
                new LocalAuthority { Code = "E07000226", Description = "Crawley" },
                new LocalAuthority { Code = "E09000008", Description = "Croydon" },
                new LocalAuthority { Code = "E07000096", Description = "Dacorum" },
                new LocalAuthority { Code = "E06000005", Description = "Darlington" },
                new LocalAuthority { Code = "E07000107", Description = "Dartford" },
                new LocalAuthority { Code = "E07000151", Description = "Daventry" },
                new LocalAuthority { Code = "W06000004", Description = "Denbighshire" },
                new LocalAuthority { Code = "E06000015", Description = "Derby" },
                new LocalAuthority { Code = "E07000035", Description = "Derbyshire Dales" },
                new LocalAuthority { Code = "E08000017", Description = "Doncaster" },
                new LocalAuthority { Code = "E06000059", Description = "Dorset" },
                new LocalAuthority { Code = "E07000108", Description = "Dover" },
                new LocalAuthority { Code = "E08000027", Description = "Dudley" },
                new LocalAuthority { Code = "E09000009", Description = "Ealing" },
                new LocalAuthority { Code = "E07000009", Description = "East Cambridgeshire" },
                new LocalAuthority { Code = "E07000040", Description = "East Devon" },
                new LocalAuthority { Code = "E07000085", Description = "East Hampshire" },
                new LocalAuthority { Code = "E07000242", Description = "East Hertfordshire" },
                new LocalAuthority { Code = "E07000137", Description = "East Lindsey" },
                new LocalAuthority { Code = "E07000152", Description = "East Northamptonshire" },
                new LocalAuthority { Code = "E06000011", Description = "East Riding of Yorkshire" },
                new LocalAuthority { Code = "E07000193", Description = "East Staffordshire" },
                new LocalAuthority { Code = "E07000244", Description = "East Suffolk" },
                new LocalAuthority { Code = "E07000061", Description = "Eastbourne" },
                new LocalAuthority { Code = "E07000086", Description = "Eastleigh" },
                new LocalAuthority { Code = "E07000030", Description = "Eden" },
                new LocalAuthority { Code = "E07000207", Description = "Elmbridge" },
                new LocalAuthority { Code = "E09000010", Description = "Enfield" },
                new LocalAuthority { Code = "E07000072", Description = "Epping Forest" },
                new LocalAuthority { Code = "E07000208", Description = "Epsom and Ewell" },
                new LocalAuthority { Code = "E07000036", Description = "Erewash" },
                new LocalAuthority { Code = "E07000041", Description = "Exeter" },
                new LocalAuthority { Code = "E07000087", Description = "Fareham" },
                new LocalAuthority { Code = "E07000010", Description = "Fenland" },
                new LocalAuthority { Code = "W06000005", Description = "Flintshire" },
                new LocalAuthority { Code = "E07000112", Description = "Folkestone and Hythe" },
                new LocalAuthority { Code = "E07000080", Description = "Forest of Dean" },
                new LocalAuthority { Code = "E07000119", Description = "Fylde" },
                new LocalAuthority { Code = "E08000037", Description = "Gateshead" },
                new LocalAuthority { Code = "E07000173", Description = "Gedling" },
                new LocalAuthority { Code = "E07000081", Description = "Gloucester" },
                new LocalAuthority { Code = "E07000088", Description = "Gosport" },
                new LocalAuthority { Code = "E07000109", Description = "Gravesham" },
                new LocalAuthority { Code = "E07000145", Description = "Great Yarmouth" },
                new LocalAuthority { Code = "E09000011", Description = "Greenwich" },
                new LocalAuthority { Code = "E07000209", Description = "Guildford" },
                new LocalAuthority { Code = "W06000002", Description = "Gwynedd" },
                new LocalAuthority { Code = "E09000012", Description = "Hackney" },
                new LocalAuthority { Code = "E06000006", Description = "Halton" },
                new LocalAuthority { Code = "E07000164", Description = "Hambleton" },
                new LocalAuthority { Code = "E09000013", Description = "Hammersmith and Fulham" },
                new LocalAuthority { Code = "E07000131", Description = "Harborough" },
                new LocalAuthority { Code = "E09000014", Description = "Haringey" },
                new LocalAuthority { Code = "E07000073", Description = "Harlow" },
                new LocalAuthority { Code = "E07000165", Description = "Harrogate" },
                new LocalAuthority { Code = "E09000015", Description = "Harrow" },
                new LocalAuthority { Code = "E07000089", Description = "Hart" },
                new LocalAuthority { Code = "E06000001", Description = "Hartlepool" },
                new LocalAuthority { Code = "E07000062", Description = "Hastings" },
                new LocalAuthority { Code = "E07000090", Description = "Havant" },
                new LocalAuthority { Code = "E09000016", Description = "Havering" },
                new LocalAuthority { Code = "E06000019", Description = "Herefordshire, County of" },
                new LocalAuthority { Code = "E07000098", Description = "Hertsmere" },
                new LocalAuthority { Code = "E07000037", Description = "High Peak" },
                new LocalAuthority { Code = "E09000017", Description = "Hillingdon" },
                new LocalAuthority { Code = "E07000132", Description = "Hinckley and Bosworth" },
                new LocalAuthority { Code = "E07000227", Description = "Horsham" },
                new LocalAuthority { Code = "E09000018", Description = "Hounslow" },
                new LocalAuthority { Code = "E07000011", Description = "Huntingdonshire" },
                new LocalAuthority { Code = "E07000120", Description = "Hyndburn" },
                new LocalAuthority { Code = "E07000202", Description = "Ipswich" },
                new LocalAuthority { Code = "W06000001", Description = "Isle of Anglesey" },
                new LocalAuthority { Code = "E06000046", Description = "Isle of Wight" },
                new LocalAuthority { Code = "E06000053", Description = "Isles of Scilly" },
                new LocalAuthority { Code = "E09000019", Description = "Islington" },
                new LocalAuthority { Code = "E09000020", Description = "Kensington and Chelsea" },
                new LocalAuthority { Code = "E07000153", Description = "Kettering" },
                new LocalAuthority { Code = "E07000146", Description = "King's Lynn and West Norfolk" },
                new LocalAuthority { Code = "E06000010", Description = "Kingston upon Hull, City of" },
                new LocalAuthority { Code = "E09000021", Description = "Kingston upon Thames" },
                new LocalAuthority { Code = "E08000034", Description = "Kirklees" },
                new LocalAuthority { Code = "E08000011", Description = "Knowsley" },
                new LocalAuthority { Code = "E09000022", Description = "Lambeth" },
                new LocalAuthority { Code = "E07000121", Description = "Lancaster" },
                new LocalAuthority { Code = "E08000035", Description = "Leeds" },
                new LocalAuthority { Code = "E06000016", Description = "Leicester" },
                new LocalAuthority { Code = "E07000063", Description = "Lewes" },
                new LocalAuthority { Code = "E09000023", Description = "Lewisham" },
                new LocalAuthority { Code = "E07000194", Description = "Lichfield" },
                new LocalAuthority { Code = "E07000138", Description = "Lincoln" },
                new LocalAuthority { Code = "E08000012", Description = "Liverpool" },
                new LocalAuthority { Code = "E06000032", Description = "Luton" },
                new LocalAuthority { Code = "E07000110", Description = "Maidstone" },
                new LocalAuthority { Code = "E07000074", Description = "Maldon" },
                new LocalAuthority { Code = "E07000235", Description = "Malvern Hills" },
                new LocalAuthority { Code = "E08000003", Description = "Manchester" },
                new LocalAuthority { Code = "E07000174", Description = "Mansfield" },
                new LocalAuthority { Code = "E06000035", Description = "Medway" },
                new LocalAuthority { Code = "E07000133", Description = "Melton" },
                new LocalAuthority { Code = "E07000187", Description = "Mendip" },
                new LocalAuthority { Code = "W06000024", Description = "Merthyr Tydfil" },
                new LocalAuthority { Code = "E09000024", Description = "Merton" },
                new LocalAuthority { Code = "E07000042", Description = "Mid Devon" },
                new LocalAuthority { Code = "E07000203", Description = "Mid Suffolk" },
                new LocalAuthority { Code = "E07000228", Description = "Mid Sussex" },
                new LocalAuthority { Code = "E06000002", Description = "Middlesbrough" },
                new LocalAuthority { Code = "E06000042", Description = "Milton Keynes" },
                new LocalAuthority { Code = "E07000210", Description = "Mole Valley" },
                new LocalAuthority { Code = "W06000021", Description = "Monmouthshire" },
                new LocalAuthority { Code = "W06000012", Description = "Neath Port Talbot" },
                new LocalAuthority { Code = "E07000091", Description = "New Forest" },
                new LocalAuthority { Code = "E07000175", Description = "Newark and Sherwood" },
                new LocalAuthority { Code = "E08000021", Description = "Newcastle upon Tyne" },
                new LocalAuthority { Code = "E07000195", Description = "Newcastle-under-Lyme" },
                new LocalAuthority { Code = "E09000025", Description = "Newham" },
                new LocalAuthority { Code = "W06000022", Description = "Newport" },
                new LocalAuthority { Code = "E07000043", Description = "North Devon" },
                new LocalAuthority { Code = "E07000038", Description = "North East Derbyshire" },
                new LocalAuthority { Code = "E06000012", Description = "North East Lincolnshire" },
                new LocalAuthority { Code = "E07000099", Description = "North Hertfordshire" },
                new LocalAuthority { Code = "E07000139", Description = "North Kesteven" },
                new LocalAuthority { Code = "E06000013", Description = "North Lincolnshire" },
                new LocalAuthority { Code = "E07000147", Description = "North Norfolk" },
                new LocalAuthority { Code = "E06000061", Description = "North Northamptonshire" },
                new LocalAuthority { Code = "E06000024", Description = "North Somerset" },
                new LocalAuthority { Code = "E08000022", Description = "North Tyneside" },
                new LocalAuthority { Code = "E07000218", Description = "North Warwickshire" },
                new LocalAuthority { Code = "E07000134", Description = "North West Leicestershire" },
                new LocalAuthority { Code = "E07000154", Description = "Northampton" },
                new LocalAuthority { Code = "E06000057", Description = "Northumberland" },
                new LocalAuthority { Code = "E07000148", Description = "Norwich" },
                new LocalAuthority { Code = "E06000018", Description = "Nottingham" },
                new LocalAuthority { Code = "E07000219", Description = "Nuneaton and Bedworth" },
                new LocalAuthority { Code = "E07000135", Description = "Oadby and Wigston" },
                new LocalAuthority { Code = "E08000004", Description = "Oldham" },
                new LocalAuthority { Code = "E07000178", Description = "Oxford" },
                new LocalAuthority { Code = "W06000009", Description = "Pembrokeshire" },
                new LocalAuthority { Code = "E07000122", Description = "Pendle" },
                new LocalAuthority { Code = "E06000031", Description = "Peterborough" },
                new LocalAuthority { Code = "E06000026", Description = "Plymouth" },
                new LocalAuthority { Code = "E06000044", Description = "Portsmouth" },
                new LocalAuthority { Code = "W06000023", Description = "Powys" },
                new LocalAuthority { Code = "E07000123", Description = "Preston" },
                new LocalAuthority { Code = "E06000038", Description = "Reading" },
                new LocalAuthority { Code = "E09000026", Description = "Redbridge" },
                new LocalAuthority { Code = "E06000003", Description = "Redcar and Cleveland" },
                new LocalAuthority { Code = "E07000236", Description = "Redditch" },
                new LocalAuthority { Code = "E07000211", Description = "Reigate and Banstead" },
                new LocalAuthority { Code = "W06000016", Description = "Rhondda Cynon Taf" },
                new LocalAuthority { Code = "E07000124", Description = "Ribble Valley" },
                new LocalAuthority { Code = "E09000027", Description = "Richmond upon Thames" },
                new LocalAuthority { Code = "E07000166", Description = "Richmondshire" },
                new LocalAuthority { Code = "E08000005", Description = "Rochdale" },
                new LocalAuthority { Code = "E07000075", Description = "Rochford" },
                new LocalAuthority { Code = "E07000125", Description = "Rossendale" },
                new LocalAuthority { Code = "E07000064", Description = "Rother" },
                new LocalAuthority { Code = "E08000018", Description = "Rotherham" },
                new LocalAuthority { Code = "E07000220", Description = "Rugby" },
                new LocalAuthority { Code = "E07000212", Description = "Runnymede" },
                new LocalAuthority { Code = "E07000176", Description = "Rushcliffe" },
                new LocalAuthority { Code = "E07000092", Description = "Rushmoor" },
                new LocalAuthority { Code = "E06000017", Description = "Rutland" },
                new LocalAuthority { Code = "E07000167", Description = "Ryedale" },
                new LocalAuthority { Code = "E08000006", Description = "Salford" },
                new LocalAuthority { Code = "E08000028", Description = "Sandwell" },
                new LocalAuthority { Code = "E07000168", Description = "Scarborough" },
                new LocalAuthority { Code = "E07000188", Description = "Sedgemoor" },
                new LocalAuthority { Code = "E08000014", Description = "Sefton" },
                new LocalAuthority { Code = "E07000169", Description = "Selby" },
                new LocalAuthority { Code = "E07000111", Description = "Sevenoaks" },
                new LocalAuthority { Code = "E08000019", Description = "Sheffield" },
                new LocalAuthority { Code = "E06000051", Description = "Shropshire" },
                new LocalAuthority { Code = "E06000039", Description = "Slough" },
                new LocalAuthority { Code = "E08000029", Description = "Solihull" },
                new LocalAuthority { Code = "E07000246", Description = "Somerset West and Taunton" },
                new LocalAuthority { Code = "E07000006", Description = "South Bucks" },
                new LocalAuthority { Code = "E07000012", Description = "South Cambridgeshire" },
                new LocalAuthority { Code = "E07000039", Description = "South Derbyshire" },
                new LocalAuthority { Code = "E06000025", Description = "South Gloucestershire" },
                new LocalAuthority { Code = "E07000044", Description = "South Hams" },
                new LocalAuthority { Code = "E07000140", Description = "South Holland" },
                new LocalAuthority { Code = "E07000141", Description = "South Kesteven" },
                new LocalAuthority { Code = "E07000031", Description = "South Lakeland" },
                new LocalAuthority { Code = "E07000149", Description = "South Norfolk" },
                new LocalAuthority { Code = "E07000155", Description = "South Northamptonshire" },
                new LocalAuthority { Code = "E07000179", Description = "South Oxfordshire" },
                new LocalAuthority { Code = "E07000126", Description = "South Ribble" },
                new LocalAuthority { Code = "E07000189", Description = "South Somerset" },
                new LocalAuthority { Code = "E07000196", Description = "South Staffordshire" },
                new LocalAuthority { Code = "E08000023", Description = "South Tyneside" },
                new LocalAuthority { Code = "E06000045", Description = "Southampton" },
                new LocalAuthority { Code = "E06000033", Description = "Southend-on-Sea" },
                new LocalAuthority { Code = "E09000028", Description = "Southwark" },
                new LocalAuthority { Code = "E07000213", Description = "Spelthorne" },
                new LocalAuthority { Code = "E07000240", Description = "St Albans" },
                new LocalAuthority { Code = "E08000013", Description = "St. Helens" },
                new LocalAuthority { Code = "E07000197", Description = "Stafford" },
                new LocalAuthority { Code = "E07000198", Description = "Staffordshire Moorlands" },
                new LocalAuthority { Code = "E07000243", Description = "Stevenage" },
                new LocalAuthority { Code = "E08000007", Description = "Stockport" },
                new LocalAuthority { Code = "E06000004", Description = "Stockton-on-Tees" },
                new LocalAuthority { Code = "E06000021", Description = "Stoke-on-Trent" },
                new LocalAuthority { Code = "E07000221", Description = "Stratford-on-Avon" },
                new LocalAuthority { Code = "E07000082", Description = "Stroud" },
                new LocalAuthority { Code = "E08000024", Description = "Sunderland" },
                new LocalAuthority { Code = "E07000214", Description = "Surrey Heath" },
                new LocalAuthority { Code = "E09000029", Description = "Sutton" },
                new LocalAuthority { Code = "E07000113", Description = "Swale" },
                new LocalAuthority { Code = "W06000011", Description = "Swansea" },
                new LocalAuthority { Code = "E06000030", Description = "Swindon" },
                new LocalAuthority { Code = "E08000008", Description = "Tameside" },
                new LocalAuthority { Code = "E07000199", Description = "Tamworth" },
                new LocalAuthority { Code = "E07000215", Description = "Tandridge" },
                new LocalAuthority { Code = "E07000045", Description = "Teignbridge" },
                new LocalAuthority { Code = "E06000020", Description = "Telford and Wrekin" },
                new LocalAuthority { Code = "E07000076", Description = "Tendring" },
                new LocalAuthority { Code = "E07000093", Description = "Test Valley" },
                new LocalAuthority { Code = "E07000083", Description = "Tewkesbury" },
                new LocalAuthority { Code = "E07000114", Description = "Thanet" },
                new LocalAuthority { Code = "E07000102", Description = "Three Rivers" },
                new LocalAuthority { Code = "E06000034", Description = "Thurrock" },
                new LocalAuthority { Code = "E07000115", Description = "Tonbridge and Malling" },
                new LocalAuthority { Code = "E06000027", Description = "Torbay" },
                new LocalAuthority { Code = "W06000020", Description = "Torfaen" },
                new LocalAuthority { Code = "E07000046", Description = "Torridge" },
                new LocalAuthority { Code = "E09000030", Description = "Tower Hamlets" },
                new LocalAuthority { Code = "E08000009", Description = "Trafford" },
                new LocalAuthority { Code = "E07000116", Description = "Tunbridge Wells" },
                new LocalAuthority { Code = "E07000077", Description = "Uttlesford" },
                new LocalAuthority { Code = "W06000014", Description = "Vale of Glamorgan" },
                new LocalAuthority { Code = "E07000180", Description = "Vale of White Horse" },
                new LocalAuthority { Code = "E08000036", Description = "Wakefield" },
                new LocalAuthority { Code = "E08000030", Description = "Walsall" },
                new LocalAuthority { Code = "E09000031", Description = "Waltham Forest" },
                new LocalAuthority { Code = "E09000032", Description = "Wandsworth" },
                new LocalAuthority { Code = "E06000007", Description = "Warrington" },
                new LocalAuthority { Code = "E07000222", Description = "Warwick" },
                new LocalAuthority { Code = "E07000103", Description = "Watford" },
                new LocalAuthority { Code = "E07000216", Description = "Waverley" },
                new LocalAuthority { Code = "E07000065", Description = "Wealden" },
                new LocalAuthority { Code = "E07000156", Description = "Wellingborough" },
                new LocalAuthority { Code = "E07000241", Description = "Welwyn Hatfield" },
                new LocalAuthority { Code = "E06000037", Description = "West Berkshire" },
                new LocalAuthority { Code = "E07000047", Description = "West Devon" },
                new LocalAuthority { Code = "E07000127", Description = "West Lancashire" },
                new LocalAuthority { Code = "E07000142", Description = "West Lindsey" },
                new LocalAuthority { Code = "E06000062", Description = "West Northamptonshire" },
                new LocalAuthority { Code = "E07000181", Description = "West Oxfordshire" },
                new LocalAuthority { Code = "E07000245", Description = "West Suffolk" },
                new LocalAuthority { Code = "E09000033", Description = "Westminster" },
                new LocalAuthority { Code = "E08000010", Description = "Wigan" },
                new LocalAuthority { Code = "E06000054", Description = "Wiltshire" },
                new LocalAuthority { Code = "E07000094", Description = "Winchester" },
                new LocalAuthority { Code = "E06000040", Description = "Windsor and Maidenhead" },
                new LocalAuthority { Code = "E08000015", Description = "Wirral" },
                new LocalAuthority { Code = "E07000217", Description = "Woking" },
                new LocalAuthority { Code = "E06000041", Description = "Wokingham" },
                new LocalAuthority { Code = "E08000031", Description = "Wolverhampton" },
                new LocalAuthority { Code = "E07000237", Description = "Worcester" },
                new LocalAuthority { Code = "E07000229", Description = "Worthing" },
                new LocalAuthority { Code = "W06000006", Description = "Wrexham" },
                new LocalAuthority { Code = "E07000238", Description = "Wychavon" },
                new LocalAuthority { Code = "E07000007", Description = "Wycombe" },
                new LocalAuthority { Code = "E07000128", Description = "Wyre" },
                new LocalAuthority { Code = "E07000239", Description = "Wyre Forest" },
                new LocalAuthority { Code = "E06000014", Description = "York" },
                new LocalAuthority { Code = "_unknown_local_authority", Description = "[Unknown Local Authority]" },
            };
        }
    }
}
